import React from "react";
import "./Rules.css";
const Rules = () => {
  return (
    <div className="rules">
      <h2>Rules For The Event Are As Follows</h2>
      <p>
        1.EACH TEAM HAS TOTAL RESOURCES WORTH OF ₹20,000 (RAW MATERIAL + HUMAN
        RESOURCE + VIRTUAL MONEY)
      </p>

      <p>
        2.TWO EXCEL SHEETS WILL BE SHARED WITH ALL THE TEAMS, FIRST ONE CONTAINS
        THE INITIAL RESOURCES OF ALL THE TEAMS AND THE SECOND ONE WILL BE A LIVE
        SHEET WHICH WILL HAVE CURRENT RESOURCES FOR EACH TEAM.
      </p>

      <p>3.THE DURATION OF THE EVENT IS 1-2 HOURS.</p>

      <p>
        4.THE GOAL IS TO PROCURE GOODS AND SERVICES FROM OTHER PARTICIPANTS AND
        PRODUCE FINISHED FINAL PRODUCTS THAT WILL HOLD A CERTAIN VALUE.
      </p>

      <p>5.EACH TEAM HAS TO COME UP WITH AT LEAST 1 FINISHED PRODUCT.</p>

      <p>
        6.THE TRANSACTIONS OF GOODS/SERVICES OR MONEY BETWEEN PARTICIPANTS WILL
        BE CARRIED OUT THROUGH THE TRADERS.
      </p>

      <p>
        7.AT ONE POINT OF TIME, ONLY TWO TEAMS CAN APPROACH A TRADER FOR
        TRANSACTIONS BETWEEN THEM. (ALL THE 2/3 MEMBERS SHOULD BE PRESENT WHILE
        CARRYING OUT THE TRADE)
      </p>

      <p>8. THE AUCTION FOR BONUS RESOURCES WILL COMMENCE ONE HOUR AFTER</p>
    </div>
  );
};
export default Rules;
